export const TRIP_CATEGORIES: string[] = [
  'Adventure',
  'Cultural',
  'Relaxation',
  'Wildlife',
  'Beach',
  'Mountain',
  'Road Trip',
  'Spiritual',
  'Trek',
  'Desert',
  'Historical',
  'Camping',

  // Core extensions
  'Nature',
  'Eco / Sustainable',
  'Luxury',
  'Budget',
  'Family',
  'Romantic / Honeymoon',
  'Solo Travel',
  'Group Travel',
  'Backpacking',

  // Experience-heavy
  'Food & Culinary',
  'Festival & Events',
  'Nightlife & Party',
  'Shopping',
  'Photography',
  'Local Experiences',
  'Art & Museums',
  'Architecture',

  // Activity-specific
  'Water Sports',
  'Winter Sports',
  'Skiing',
  'Scuba Diving',
  'Snorkeling',
  'Surfing',
  'Cycling',
  'Motorbike Trip',
  'Safari',
  'Bird Watching',
  'Stargazing',

  // Purpose-driven
  'Wellness & Retreat',
  'Yoga',
  'Meditation',
  'Medical',
  'Educational',
  'Business',
  'Workation',
  'Volunteer',

  // Format / style
  'Weekend Getaway',
  'Long Stay',
  'City Exploration',
  'Rural / Village',
  'Offbeat / Hidden Gems',
  'Luxury Train',
  'Cruise',

  // Social vibe
  'Party Trip',
  'Digital Nomad',
  'Influencer / Content',

  'Other',
] as const

export const INDIAN_STATES = [
    'Andhra Pradesh',
    'Arunachal Pradesh',
    'Assam',
    'Bihar',
    'Chhattisgarh',
    'Goa',
    'Gujarat',
    'Haryana',
    'Himachal Pradesh',
    'Jharkhand',
    'Karnataka',
    'Kerala',
    'Madhya Pradesh',
    'Maharashtra',
    'Manipur',
    'Meghalaya',
    'Mizoram',
    'Nagaland',
    'Odisha',
    'Punjab',
    'Rajasthan',
    'Sikkim',
    'Tamil Nadu',
    'Telangana',
    'Tripura',
    'Uttar Pradesh',
    'Uttarakhand',
    'West Bengal',
    'Andaman and Nicobar Islands',
    'Chandigarh',
    'Dadra and Nagar Haveli and Daman and Diu',
    'Delhi',
    'Jammu and Kashmir',
    'Ladakh',
    'Lakshadweep',
    'Puducherry'
  ] as const


export const TRIP_TYPES = [
  { value: 'group_tour', label: 'Group Tour' },
  { value: 'group_trek', label: 'Group Trek' },
  { value: 'bike_trip', label: 'Bike Trip' },
] as const

/** Countries list — India is placed first for quick access */
export const COUNTRIES: string[] = [
  'India',
  'Afghanistan',
  'Albania',
  'Algeria',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahrain',
  'Bangladesh',
  'Belgium',
  'Bhutan',
  'Bolivia',
  'Brazil',
  'Bulgaria',
  'Cambodia',
  'Canada',
  'Chile',
  'China',
  'Colombia',
  'Croatia',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Ecuador',
  'Egypt',
  'Estonia',
  'Ethiopia',
  'Finland',
  'France',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Hungary',
  'Iceland',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lithuania',
  'Luxembourg',
  'Malaysia',
  'Maldives',
  'Malta',
  'Mexico',
  'Mongolia',
  'Morocco',
  'Myanmar',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nigeria',
  'Norway',
  'Oman',
  'Pakistan',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Qatar',
  'Romania',
  'Russia',
  'Saudi Arabia',
  'Serbia',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'South Africa',
  'South Korea',
  'Spain',
  'Sri Lanka',
  'Sweden',
  'Switzerland',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'Vietnam',
  'Yemen',
  'Zimbabwe',
]

export const TRIP_DIFFICULTIES = [
  { value: 'easy', label: 'Easy' },
  { value: 'moderate', label: 'Moderate' },
  { value: 'challenging', label: 'Challenging' },
] as const

export const ADD_ON_CATEGORIES = [
  { value: 'extra_activity', label: 'Extra Activity' },
  { value: 'room_upgrade', label: 'Room Upgrade' },
  { value: 'bike_upgrade', label: 'Bike Upgrade' },
  { value: 'service', label: 'Service' },
  { value: 'others', label: 'Others' },
] as const

export const FORM_STEPS = [
  { id: 1, title: 'Basic Information', description: 'Trip details and location' },
  { id: 2, title: 'Pricing', description: 'Pricing tiers and add-ons' },
  { id: 3, title: 'Itinerary', description: 'Day-wise trip plan' },
  { id: 4, title: 'Inclusions & Exclusions', description: "What's included and excluded" },
  { id: 5, title: 'Media & FAQ', description: 'Images and questions' },
] as const

export const VALIDATION_RULES = {
  MIN_TAGS: 7,
  MIN_IMAGES: 5,
  MIN_FAQS: 4,
  MAX_IMAGE_SIZE: 10 * 1024 * 1024, // 10MB
  ACCEPTED_IMAGE_TYPES: ['image/png', 'image/jpeg', 'image/jpg'],
  MIN_ITINERARY_DAYS: 1,
  MIN_INCLUSIONS: 3,
  MIN_EXCLUSIONS: 2,
  MIN_HIGHLIGHTS: 2,
  MAX_ITINERARY_WORDS: 100,
  MIN_BASE_PRICE: 0,
  MIN_MAX_PRICE: 0,
} as const

/**
 * All validation error messages in one place.
 * Update messages here and they will be reflected in both the
 * validateTripForm function and any form UI that references them.
 */
export const VALIDATION_MESSAGES = {
  // Basic info
  title: 'Trip title is required',
  description: 'Trip description is required',
  category: 'At least one category is required',
  tags: `At least ${VALIDATION_RULES.MIN_TAGS} tags are required`,
  // Location
  locationCity: 'City is required',
  locationState: 'State is required',
  // Media & FAQ
  tripImages: `At least ${VALIDATION_RULES.MIN_IMAGES} trip images are required`,
  faqs: `At least ${VALIDATION_RULES.MIN_FAQS} FAQs are required`,
  // Pricing
  pricings: 'At least one pricing tier is required',
  advanceBookingPrice: 'Advance booking price must be greater than 0 when advance booking is enabled',
  // Itinerary
  itinerary: `At least ${VALIDATION_RULES.MIN_ITINERARY_DAYS} itinerary day is required`,
  // Inclusions / exclusions / highlights
  inclusions: `At least ${VALIDATION_RULES.MIN_INCLUSIONS} inclusions are required`,
  exclusions: `At least ${VALIDATION_RULES.MIN_EXCLUSIONS} exclusions are required`,
  highlights: `At least ${VALIDATION_RULES.MIN_HIGHLIGHTS} highlights are required`,
  // Per-item dynamic messages
  pricingTierLabel: (index: number) => `Pricing tier ${index + 1}: Label is required`,
  pricingTierPrice: (index: number) => `Pricing tier ${index + 1}: Price per person cannot be negative`,
  pricingTierQuantity: (index: number) => `Pricing tier ${index + 1}: Max quantity must be at least 1`,
  addonLabel: (index: number) => `Add-on ${index + 1}: Label is required`,
  addonPrice: (index: number) => `Add-on ${index + 1}: Price per person cannot be negative`,
  itineraryDayTitle: (dayNumber: number) => `Day ${dayNumber} title is required`,
  itineraryDayDescription: (dayNumber: number) => `Day ${dayNumber} itinerary description is required`,
  itineraryDayWordCount: (dayNumber: number) =>
    `Day ${dayNumber} itinerary exceeds ${VALIDATION_RULES.MAX_ITINERARY_WORDS} words limit`,
}

export const IMAGE_UPLOAD_CONFIG = {
  maxSize: VALIDATION_RULES.MAX_IMAGE_SIZE,
  acceptedTypes: VALIDATION_RULES.ACCEPTED_IMAGE_TYPES,
  minRequired: VALIDATION_RULES.MIN_IMAGES,
} as const

export const PHOTO_TIPS = [
  'Use high-resolution images (at least 1920x1080px)',
  'Show diverse aspects: landscapes, activities, accommodations',
  'Include photos of previous trips if available',
  'Avoid heavily edited or filtered images',
  'Ensure you have rights to use the images',
] as const
